Create kanishkasrivastava
aravindvnair99/Algorithms pull request #27
Opened 2021-10-29 15:59 UTC by kanishkasrivastava

Fixes #

## Proposed Changes

-
-
-

2021-10-29 17:19 UTC, aravindvnair99 reviewed
@kanishkasrivastava The file is missing an extension.

2021-10-30 03:14 UTC, kanishkasrivastava commented
What kind of extension please accept the pull requests

On Fri, 29 Oct 2021, 10:50 pm pull-request-attention[bot], <
***@***.***> wrote:

> Assigned #27
> <https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/27>
> to @kanishkasrivastava <https://github.com/kanishkasrivastava>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/27#event-5541902409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRAZRPT45R2D2UU7MJQLSTUJLJUHANCNFSM5G7U3PVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-30 09:49 UTC, kanishkasrivastava commented
All changes done


On Fri, 29 Oct 2021 at 22:50, pull-request-attention[bot] <
***@***.***> wrote:

> Assigned #27
> <https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/27>
> to @kanishkasrivastava <https://github.com/kanishkasrivastava>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/27#event-5541902409>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARRAZRPT45R2D2UU7MJQLSTUJLJUHANCNFSM5G7U3PVQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-30 10:00 UTC, kanishkasrivastava reviewed
Happy hacktoberfest

2021-10-30 10:27 UTC, aravindvnair99 requested changes
@kanishkasrivastava Your file is still missing an extension. C++ files should end with `.cpp` extension.

2021-10-30 10:27 UTC, aravindvnair99 commented on kanishkasrivastava
> +Hello there
```suggestion
```

Adding this here will lead to a compilation error.

2021-10-30 10:41 UTC, kanishkasrivastava reviewed
All issues solved

2021-10-30 16:13 UTC, aravindvnair99 requested changes

2021-10-30 16:13 UTC, aravindvnair99 commented on kanishkasrivastava.cpp
> +
```suggestion
```

2021-10-30 16:13 UTC, aravindvnair99 commented on kanishkasrivastava.cpp
> +Hello there
```suggestion
```

2021-10-30 16:13 UTC, aravindvnair99 commented on kanishkasrivastava.cpp
> +is a genral code for beginners in c++
```suggestion
```

2021-10-30 16:13 UTC, aravindvnair99 commented on kanishkasrivastava.cpp
> +
```suggestion
```

2021-10-30 16:13 UTC, aravindvnair99 commented on kanishkasrivastava.cpp
> +	check2();
Since this is just one function, code could be directly put here instead of calling a function from here.

2021-10-30 16:14 UTC, aravindvnair99 commented
> All issues solved

@kanishkasrivastava Please take a look at the lines I have highlighted.

2021-10-30 16:18 UTC, aravindvnair99 commented
Duplicate of #29

2021-10-30 16:18 UTC, closed without merging

2021-10-30 16:26 UTC, kanishkasrivastava commented
DONE