Added Time format Converter
aravindvnair99/Algorithms pull request #8
Opened 2020-10-03 03:55 UTC by AvinashSubhash

#7

2020-10-03 09:14 UTC, aravindvnair99 requested changes
@AvinashSubhash Could you remove the extra spaces and lines?

2020-10-03 09:23 UTC, AvinashSubhash reviewed
Done

2020-10-03 09:26 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +    result = time_conversion(s)
You have missed printing the output here.

2020-10-03 09:27 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +    print("Enter the time: (HH:MM:SSPM or HH:MM:SSAM") #Here the last two characters of the string denotes AM or PM"
Close the bracket and also it might look better with a space between AM and PM and the seconds.

2020-10-03 09:27 UTC, aravindvnair99 requested changes
There are a few issues that need to be fixed before I can merge it.

2020-10-03 09:33 UTC, AvinashSubhash reviewed
I have added the print statement and added a space between seconds and AM/PM in input and output format

2020-10-03 21:03 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +    print("Converted Time: ",result)
```suggestion
    print("Converted Time: ", time_conversion(s))
```

2020-10-03 21:04 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +    print("Enter the time: (HH:MM:SS PM or HH:MM:SS AM)") #Here the last two characters of the string denotes AM or PM"
```suggestion
    print("Enter the time: (HH:MM:SS PM or HH:MM:SS AM)")
```

2020-10-03 21:06 UTC, aravindvnair99 requested changes
Nice! You fixed all the issues. But if the user enters `12:09:23`, then the program crashes. Instead, it would be better to ask the user to re-enter a valid input.

2020-10-04 02:37 UTC, AvinashSubhash reviewed
The crashing problem has been fixed and statements have been added to check the format of the input

2020-10-04 09:48 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +            print("Invalid Input.Enter the value again!")
```suggestion
            print("Invalid Input. Enter the value again!")
```

2020-10-04 09:52 UTC, aravindvnair99 requested changes
Try entering input as `aaaaaaaaaaa`

2020-10-04 10:43 UTC, AvinashSubhash reviewed
I have covered all the conditions :-)

2020-10-11 09:50 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +
```suggestion
```

2020-10-11 09:51 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +
```suggestion
```

2020-10-11 09:51 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +        print("Invalid Input.Enter the value again!")
```suggestion
        print("Invalid Input. Enter the value again!")
```

2020-10-11 09:51 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +    print("Converted Time: ", time_conversion(s))
```suggestion
    print("Converted Time:", time_conversion(s))
```

2020-10-11 09:53 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +        return(str(0)+str(hour)+s[2:8])
```suggestion
        return(str(0)+str(hour)+s[2:8])

```

2020-10-11 09:53 UTC, aravindvnair99 commented on Python/time_format_converter.py
> +flag = True
```suggestion
flag = True
   
```

2020-10-11 09:53 UTC, aravindvnair99 approved these changes
Nice work @AvinashSubhash!

2020-10-11 09:57 UTC, aravindvnair99 requested changes
@AvinashSubhash  Have a look at the issues pointed out by CodeFactor as well [here](https://github.com/DSC-ASEB/Getting-started-with-Hacktoberfest/pull/8/checks?check_run_id=1237845902).

2020-10-18 09:25 UTC, aravindvnair99 commented
@AvinashSubhash 👀

2020-10-20 17:02 UTC, aravindvnair99 requested changes
@AvinashSubhash Please recheck. The output is wrong.

2020-10-20 17:03 UTC, aravindvnair99 commented
@AvinashSubhash Moving this PR to draft. Once you are done with your changes, you can mark as `Ready for review`.

2020-10-23 05:18 UTC, aravindvnair99 commented
@AvinashSubhash Reminder: If you fix the pending issues stated above, I will merge this pull request. On the other hand, inactivity will lead to the pull request being closed without merging.

2020-10-23 11:02 UTC, aravindvnair99 requested changes
@AvinashSubhash Nice work! Try `10:00:00 AM` 10 and 11 have extra zero in the beginning. That's the only bug left, I guess.

2020-10-23 18:16 UTC, aravindvnair99 requested changes
@AvinashSubhash Try `12:00:00` series. The output is `None` which is not right.

2020-10-24 21:04 UTC, aravindvnair99 approved these changes

2020-10-24 21:17 UTC, merged